### PR TITLE
Backwards compatible Python 3 support.

### PR DESCRIPTION
**Pull request by Danilka**
I also cleaned up some code. I hope that's ok.

### CODE REVIEW

**Comment by bunop** [comment]
Nice Work! I like the pep8 coding style. The test failing in CI could be a transitory problem in EnsEMBL endpoint

**Comment by gawbul** [comment]
Hi, @Danilka, thanks for the PR. Will have a look at the Travis build in see if I can figure out what the issue is. Will get this merged asap 👍

**Comment by Danilka** [comment]
Thanks for the quick response guys!
I checked the tests, it is indeed EnsEMBL. It randomly spits out 500s when it feels like it. Both on API and curl side. We might want to consider to build in retries for these cases.

**Comment by gawbul** [comment]
Yeah, I was just testing this myself, and it was randomly not working for the info/genomes/taxonomy endpoint.

**Pull request merged**
